image: python:3.9

stages:
  - lint
  - build
  - deploy

Lint:
  stage: lint
  before_script:
    - make install
  script:
    - make lint

Complexity:
  stage: lint
  before_script:
    - make install
  script:
    - make complexity

Build:
  stage: build
  only:
    - master
  before_script:
    - pip3 install -r requirements.txt
    - sudo apt update && sudo apt install python3-testresources -y
    - pip3 install --user --upgrade setuptools wheel
    - pip3 install twine
  script:
    - make build
    - twine check dist/*
  artifacts:
    paths:
      - dist/
    expire_in: 1 day

Deploy:
  stage: deploy
  only: 
    - master
  before_script:
    - pip3 install twine
  script:
    - twine upload -u $PYPI_USER -p $PYPI_PASS dist/*
